site_name: CloudAI docs
theme:
  name: material
nav:
  - Home: index.md
  - Agents: agents.md
  - Tokenomics: tokenomics.md
  - Allocation: allocation.md
  - Staking: staking.md
  - Staking APR: staking_apr.md

# Change build output directory to website/docs/
site_dir: ../website/docs

